import type { SupportedLocale } from '../../i18n/runtime';

const simplifiedChinese: Record<string, string> = {
  Load: '载入',
  Download: '下载',
  Resize: '缩放',
  Crop: '裁剪',
  Flip: '翻转',
  Rotate: '旋转',
  Draw: '绘制',
  Shape: '形状',
  Icon: '图标',
  Text: '文字',
  Mask: '蒙版',
  Filter: '滤镜',
  History: '历史',
  Undo: '撤销',
  Redo: '重做',
  Reset: '重置',
  Delete: '删除',
  'Delete-all': '全部删除',
  'Zoom In': '放大',
  'Zoom Out': '缩小',
  Hand: '拖动画布',
  Width: '宽度',
  Height: '高度',
  'Lock Aspect Ratio': '锁定宽高比',
  Apply: '应用',
  Cancel: '取消',
  Custom: '自由',
  Square: '正方形',
  'Flip X': '水平翻转',
  'Flip Y': '垂直翻转',
  Free: '自由线',
  Straight: '直线',
  Color: '颜色',
  Range: '范围',
  Rectangle: '矩形',
  Circle: '圆形',
  Triangle: '三角形',
  Fill: '填充',
  Stroke: '描边',
  Bold: '粗体',
  Italic: '斜体',
  Underline: '下划线',
  Left: '左对齐',
  Center: '居中',
  Right: '右对齐',
  'Text size': '文字大小',
  Grayscale: '灰度',
  Invert: '反色',
  Sepia: '棕褐色',
  Blur: '模糊',
  Sharpen: '锐化',
  Emboss: '浮雕',
  Brightness: '亮度',
  Noise: '噪点',
  Pixelate: '像素化',
  Sepia2: '棕褐色 2',
  'Remove White': '去除白色',
  Distance: '距离',
  'Color Filter': '颜色滤镜',
  Threshold: '阈值',
  Tint: '色调',
  Multiply: '正片叠底',
  Blend: '混合',
  Arrow: '箭头',
  'Arrow-2': '箭头 2',
  'Arrow-3': '箭头 3',
  'Star-1': '星形 1',
  'Star-2': '星形 2',
  Polygon: '多边形',
  Location: '定位',
  Heart: '心形',
  Bubble: '对话气泡',
  'Custom icon': '自定义图标',
  'Load Mask Image': '载入蒙版图片',
};

const traditionalChinese: Record<string, string> = {
  ...simplifiedChinese,
  Load: '載入',
  Download: '下載',
  Resize: '縮放',
  Crop: '裁剪',
  Flip: '翻轉',
  Rotate: '旋轉',
  Draw: '繪製',
  Shape: '形狀',
  Icon: '圖示',
  Text: '文字',
  Mask: '遮罩',
  Filter: '濾鏡',
  History: '歷史',
  Undo: '復原',
  Redo: '重做',
  Reset: '重設',
  Delete: '刪除',
  'Delete-all': '全部刪除',
  'Zoom In': '放大',
  'Zoom Out': '縮小',
  Hand: '拖動畫布',
  Width: '寬度',
  Height: '高度',
  'Lock Aspect Ratio': '鎖定長寬比',
  Apply: '套用',
  'Flip X': '水平翻轉',
  'Flip Y': '垂直翻轉',
  Free: '自由線',
  Straight: '直線',
  Color: '顏色',
  Rectangle: '矩形',
  Circle: '圓形',
  Triangle: '三角形',
  Fill: '填滿',
  Stroke: '描邊',
  Bold: '粗體',
  Italic: '斜體',
  Underline: '底線',
  Left: '靠左',
  Center: '置中',
  Right: '靠右',
  'Text size': '文字大小',
  Grayscale: '灰階',
  Invert: '負片',
  Blur: '模糊',
  Sharpen: '銳化',
  Brightness: '亮度',
  Noise: '雜訊',
  Pixelate: '像素化',
  Sepia2: '棕褐色 2',
  'Remove White': '移除白色',
  Distance: '距離',
  'Color Filter': '顏色濾鏡',
  Threshold: '閾值',
  Tint: '色調',
  Multiply: '色彩增值',
  Blend: '混合',
  Arrow: '箭頭',
  'Arrow-2': '箭頭 2',
  'Arrow-3': '箭頭 3',
  'Star-1': '星形 1',
  'Star-2': '星形 2',
  Polygon: '多邊形',
  Location: '定位',
  Heart: '心形',
  Bubble: '對話氣泡',
  'Custom icon': '自訂圖示',
  'Load Mask Image': '載入遮罩圖片',
};

export function toastEditorLocale(locale: SupportedLocale): Record<string, string> {
  if (locale === 'zh-CN') return simplifiedChinese;
  if (locale === 'zh-TW') return traditionalChinese;
  return {};
}

const TRANSPARENT_PIXEL = 'data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';

export const TOAST_EDITOR_THEME: Record<string, string> = {
  'common.bi.image': TRANSPARENT_PIXEL,
  'common.bisize.width': '0px',
  'common.bisize.height': '0px',
  'common.backgroundImage': 'none',
  'common.backgroundColor': 'var(--editor-background)',
  'common.border': '0px',
  'header.backgroundImage': 'none',
  'header.backgroundColor': 'var(--editor-surface)',
  'header.border': '0px',
  'loadButton.backgroundColor': 'var(--editor-button)',
  'loadButton.border': '1px solid var(--editor-border)',
  'loadButton.color': 'var(--editor-text)',
  'downloadButton.backgroundColor': '#2563eb',
  'downloadButton.border': '1px solid #2563eb',
  'downloadButton.color': '#ffffff',
  'menu.normalIcon.color': 'var(--editor-icon)',
  'menu.activeIcon.color': 'var(--editor-icon-active)',
  'menu.disabledIcon.color': 'var(--editor-icon-disabled)',
  'menu.hoverIcon.color': 'var(--editor-icon-active)',
  'submenu.normalIcon.color': 'var(--editor-icon)',
  'submenu.activeIcon.color': 'var(--editor-icon-active)',
  'submenu.backgroundColor': 'var(--editor-surface)',
  'submenu.partition.color': 'var(--editor-border)',
  'submenu.normalLabel.color': 'var(--editor-muted)',
  'submenu.activeLabel.color': 'var(--editor-text)',
  'range.pointer.color': 'var(--editor-icon-active)',
  'range.bar.color': 'var(--editor-border)',
  'range.subbar.color': '#2563eb',
  'range.value.color': 'var(--editor-text)',
  'range.value.border': '1px solid var(--editor-border)',
  'range.value.backgroundColor': 'var(--editor-button)',
  'range.title.color': 'var(--editor-text)',
  'colorpicker.button.border': '1px solid var(--editor-border)',
  'colorpicker.title.color': 'var(--editor-text)',
};
